backend:
  name: git-gateway
  branch: main
media_folder: public/assets/images
public_folder: assets/images
collections:
  - name: settings
    label: Settings
    files:
      - label: General
        name: general
        file: content/settings.md
        fields:
          - label: "Social Media"
            name: "socialMedia"
            widget: "object" 
            fields:
              - {label: "Facebook", name: "facebook", widget: string, required: false}
              - {label: "Twitter", name: "twitter", widget: string, required: false}
              - {label: "Instagram", name: "instagram", widget: string, required: false}
          - label: "Business Info"
            name: "businessInfo"
            widget: "object" 
            fields:
              - {label: "Name", name: "name", widget: string, required: false}
              - {label: "Address Line 1", name: "address1", widget: string, required: true, hint: House Number and Street}
              - {label: "Address Line 2", name: "address2", widget: string, required: false, hint: Apt/Unit/Suite Number}
              - {label: "City", name: "city", widget: string, required: true}
              - {label: "State", name: "state", widget: string, required: true}
              - {label: "Zip Code", name: "zip", widget: string, required: true}
              - {label: "Phone", name: "phone", widget: string, required: false, pattern: ['((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}', "Must be in format (000) 000-0000"], hint: Format (000) 000-0000}
              - {label: "Email", name: "email", widget: string, required: true}
  - name: pages
    label: Pages
    files:
    - label: Home
      name: home
      file: content/home.md
      fields:
        - { label: Title, name: title, widget: string}
        - { label: Tagline, name: tagline, widget: string }
        - { label: Body, name: body, widget: markdown}
        - { label: Images Heading, name: imagesHeading, widget: string }
        - label: Images
          name: images
          widget: object 
          fields:
            - label: Left Image
              name: imgLeft
              widget: object
              fields:
                - { label: Image, name: img, widget: image }
                - { label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Middle Image
              name: imgMiddle
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Right Image
              name: imgRight
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}
        - { label: Reviews Heading, name: reviewsHeading, widget: string }
        - label: Reviews
          name: reviews
          collapsed: false
          widget: list
          fields:
            - {label: Quote, name: quote, widget: text }
            - {label: Client, name: client, widget: string }
            - {label: Location, name: location, widget: string, required: false }
        - { label: About Button Text, name: aboutCTA, widget: string }
        
    - label: About
      name: about
      file: content/about.md
      fields:
        - { label: Title, name: title, required: false, widget: string}
        - { label: Body, name: body, required: false, widget: markdown}
        - { label: Services Button Text, name: servicesCTA, widget: string}

    - label: Boarding
      name: boarding
      file: content/boarding.md
      fields:
        - { label: Title, name: title, required: false, widget: string}
        - { label: Body, name: body, required: false, widget: markdown}
        - { label: FAQ Button Text, name: faqCTA, widget: string}
        - label: Images
          name: images
          widget: object 
          fields:
            - label: Left Image
              name: imgLeft
              widget: object
              fields:
                - { label: Image, name: img, widget: image }
                - { label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Middle Image
              name: imgMiddle
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Right Image
              name: imgRight
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}

    - label: Grooming
      name: grooming
      file: content/grooming.md
      fields:
        - { label: Title, name: title, required: false, widget: string}
        - { label: Body, name: body, required: false, widget: markdown}
        - { label: FAQ Button Text, name: faqCTA, widget: string}
        - label: Images
          name: images
          widget: object 
          fields:
            - label: Left Image
              name: imgLeft
              widget: object
              fields:
                - { label: Image, name: img, widget: image }
                - { label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Middle Image
              name: imgMiddle
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}
            - label: Right Image
              name: imgRight
              widget: object
              fields:
                - {label: Image, name: img, widget: image}
                - {label: Description, name: alt, widget: string, hint: very short generic description}
        
    - label: FAQ
      name: faq
      file: content/faq.md
      fields:
        - { label: Title, name: title, required: false, widget: string}
        - { label: Body, name: body, required: false, widget: markdown}
        - label: Questions and Answers
          name: faqs
          widget: list
          fields:
            - {label: Question, name: question, widget: text, default: [write the question here]}
            - {label: Answer, name: answer, widget: markdown, default: [write the answer here]}
        - { label: Contact Button Text, name: contactCTA, widget: string }
    
    - label: Contact
      name: contact
      file: content/contact.md
      fields:
        - { label: Title, name: title, required: false, widget: string}
        - { label: Message, name: message, widget: string}